import Head from "next/head";
import Tasks from "~/components/Tasks/Tasks";
import { useGlobalContext } from "~/context/GlobalProvider";

export default function Home() {
  const { tasks } = useGlobalContext();

  return (
    // <>
    //   <Head>
    //     <title>Task Management App</title>
    //     <meta name="description" content="Generated by create-t3-app" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>
    //   <main className="w-full h-full">
    //     <Tasks title="All Tasks" tasks={tasks} />
    //   </main>
    // </>
    <Tasks title="All Tasks" tasks={tasks} />
  );
}
